# Helmfile
#
#   Input env variables:
#     - STACK: [ integration | staging | prod ]
#     - HELMFILE_RELEASES_LIST: 
#         List of release names to install, separated by "|"
#           E.g. "kafka-manager|kafka-rest-proxy"
#         It would be cool to get this list from the list of subdirs under /helm/charts
#         However, we cannot access dir listing functionality from Helmfile's GoTemplate context
#
#   To install/upgrade all the specified releases:
#     $ helmfile apply
#
#   To install/upgrade only one specific release:
#     $ helmfile \
#         --selector release-name=kafka-manager \
#         apply
#   
#   To delete releases, same as above with: helmfile delete/destroy
#

helmDefaults:
  tillerNamespace: kube-system

{{ $releases := splitList "|" (requiredEnv "HELMFILE_RELEASES_LIST") }}

releases:
  {{- range $releases }}
  - name: {{ . }}
    chart: ./charts/{{ . }}
    namespace: demo
    labels:
      release-name: {{ . }}
    values:
      - ./values-global.yaml
      - ./charts/{{ . }}/values-{{ requiredEnv "STACK" }}.yaml
    missingFileHandler: error
  {{- end }}
