# Init Helm
helm init



# Install Flux Operator in "cluster" mode.
# In this mode the FO will be able to deploy a Flux instances in any namespace,
# stated in the Flux CRD resource that we deploy to Kube.
# The provided Deployment installs the FluxOp in the "default" namespace.
kubectl apply -f https://raw.githubusercontent.com/justinbarrick/flux-operator/master/deploy/flux-operator-cluster.yaml

# Watch Flux Operator (ns "default")
watch kubectl get all -n default
kubectl logs -f $(kubectl get pods -o name -n default | grep flux-operator) -n default



# Although the FluxOp can actually install HelmOp instances along with the Flux
# ones, FluxOp doesn't support the latest HelmOp versions.
# Therefore we install HelmOp ourselves globally using its chart.
helm repo add fluxcd https://charts.fluxcd.io
helm install \
    --name helm-operator \
    --namespace flux \
	--set createCRD=true \
	fluxcd/helm-operator
kubectl api-resources | grep flux
	# We have a new resource kind: helmrelease

# Watch the HelmOperator at work
watch helm status helm-operator
kubectl logs -f $(kubectl get pods -o name -n flux | grep helm-operator) -n flux



# Deploy the Flux config
kubectl create namespace team-kolontai
kubectl apply -n team-kolontai -f ./team-kolontai.flux.yaml

# Watch the Flux instance created by the FluxOp
watch kubectl get all -n team-kolontai
kubectl logs -f $(kubectl get pods -n team-kolontai -o name | grep flux | grep -v memcached) -n team-kolontai

# Get autogenerated SSH key from the created Flux instance
# Add it to GitHub repo, read/write access (more on this later)
fluxctl identity --k8s-fwd-ns team-kolontai



# Watch the resources created by the autogenerated Flux instance
watch "kubectl get helmreleases -n team-kolontai ; echo; kubectl get all -n team-kolontai"



# Undo
helm delete --purge helm-operator
kubectl delete -f https://raw.githubusercontent.com/justinbarrick/flux-operator/master/deploy/flux-operator-cluster.yaml
kubectl delete $(kubectl get crd -o name | grep flux)
kubectl delete namespace flux
kubectl delete namespace team-kolontai
helm delete --purge mysql
helm reset
helm repo remove fluxcd
