{{- if .Values.clusters -}}
{{- $scriptHash := include (print $.Template.BasePath "/configmap.yaml") . | sha256sum | trunc 8 -}}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ template "kafka-manager.bootstrap-job-name" . }}-{{ $scriptHash }}"
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: {{ include "kafka-manager.app-name" . }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | replace "+" "_" | trunc 63 }}
    helm.sh/chart: {{ include "kafka-manager.chart" . }}
spec:
  template:
    metadata:
      labels:
        app: {{ template "kafka-manager.app-name" . }}
        release: {{ .Release.Name }}
    spec:
      restartPolicy: OnFailure
      volumes:
        - name: script-volume
          configMap:
            name: {{ template "kafka-manager.bootstrap-configmap-name" . }}
            defaultMode: 0744
      containers:
        - name: {{ .Chart.Name }}-bootstrap
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/usr/local/script/addClusters.sh"]
          env:
            - name: KAFKA_MANAGER_AUTH_ENABLED
              value: {{ .Values.basicAuth.enabled | quote }}
            - name: KAFKA_MANAGER_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ template "kafka-manager.secret-name" . }}
                  key: basicAuthUsername
            - name: KAFKA_MANAGER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ template "kafka-manager.secret-name" . }}
                  key: basicAuthPassword
          volumeMounts:
            - name: script-volume
              mountPath: "/usr/local/script"
  backoffLimit: 20
{{- end -}}
