helm init

# Install Flux

helm repo add fluxcd https://charts.fluxcd.io

helm install \
	--name flux \
	--set helmOperator.create=true \
    --set helmOperator.createCRD=true \
	--set git.url=git@github.com:kodachimaru/gitops-demo-flux-1-automated-releases.git \
	--set git.pollInterval=5s \
	--namespace flux \
	fluxcd/flux

watch helm status flux



# Get autogenerated SSH key
# Add it to GitHub repo, read/write access (more on this later)
kubectl -n flux logs deployment/flux | grep identity.pub | cut -d '"' -f2



# Watch Flux installing the resources
kubectl logs -f $(kubectl get pods -n flux -o name | grep flux | grep -v helm | grep -v memcached) -n flux
# Watch the HelmRelease being installed 
watch helm status mysql



# Kill NGINX deployment and watch it resurrect
kubectl delete deployment nginx-deployment
watch kubectl get deployments

# Kill MySQL Helm release and watch it resurrect
helm delete --purge mysql
watch helm list

# Delete MySQL HelmRelease resource, and watch:
#	- The "mysql" release being killed by HelmOperator
#	- The "mysql" HelmRelease resource being recreated from git
#	- The "mysql" release being redeployed by HelmOperator
kubectl delete helmrelease mysql
watch "echo ------ HELM LIST ; helm list ; echo '------ HELMRELEASE LIST' ; kubectl get helmrelease"



# Undo
helm delete --purge flux
helm delete --purge mysql
kubectl delete deployment nginx-deployment
kubectl delete $(kubectl get crd -o name | grep flux)
helm reset

